### ISSUE TITLE
Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by connor11528** [mk30/portfoliosite#1]
Tried to run this repo, hit an error.

```
/Users/cleech/Projects/portfoliosite/router.js:5
        h('div.gallery', m.state.files.map(function (x) {
                                      ^
TypeError: Cannot read property 'map' of undefined
    at Object.fn (/Users/cleech/Projects/portfoliosite/router.js:5:39)
    at /Users/cleech/Projects/portfoliosite/server.js:16:26
    at FSReqWrap.oncomplete (fs.js:95:15)
```

Is this the source code for crazy trance site http://kitties.neocities.org/?

Also ran `npm install routes --save`

**Comment by mk30** [comment]
sorry about that. added routes to package.json. let me know if you get the error after you have routes installed.

this is not the source code for the neocities site...this is the source code for a personal portfolio site i'm working on. the neocities site is all html, css, and browser javascript. you can view the source to see it.

**Comment by connor11528** [comment]
okay this is some crazy matrix code. i didn't know about the hyperstream and virtual-dom packages
